name: Publish Beta Package

# This workflow is triggered on a label being added to a PR, and will publish a beta version of the bundle to npm
# Use `yarn changeset pre beta` to enter a pre-release state then add a pre-release changeset with `yarn changeset add`
# This action will fail if you have not entered pre-release state
on:
  pull_request:
    types: [labeled]

permissions: write-all

jobs:
  has-permission:
    name: Check permissions
    runs-on: ubuntu-latest
    steps:
      - name: 'Check if user has admin access'
        uses: 'lannonbr/repo-permission-check-action@2.0.2'
        with:
          permission: 'admin'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release:
    name: '@guardian/commercial'
    runs-on: ubuntu-latest
    needs: has-permission
    if: github.event.label.name == '[beta] @guardian/commercial'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check for pre-release
        run: test -f .changeset/pre.json

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build package
        run: yarn build

      - name: Create Release
        uses: changesets/action@v1
        id: changeset
        with:
          publish: yarn changeset publish

      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const publishedPackages = ${{ steps.changeset.outputs.publishedPackages }};
            const version = publishedPackages[0].version;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 ${version} published to npm as a beta release`
            })
