name: Changesets

on:
  push:
    branches:
      - main

jobs:
  changesets-version:
    name: Changesets Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          # Fetch all Git history so that Changesets can generate changelogs
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          cache: "yarn"
          node-version-file: ".nvmrc"

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: yarn changeset publish
          title: '🦋 Release package updates'
          commit: "Bump version"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
