name: CI Bundle
on:
  push:
    branches:
      - "main"
  pull_request:
    branches-ignore:
      - "gh-pages"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

  test:
    name: Test
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Run unit tests
        run: yarn test --ci
        working-directory: bundle

  lint:
    name: Lint
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Lint files
        run: yarn lint
        working-directory: bundle

      - name: Check formatting
        run: yarn prettier:check
        working-directory: bundle

  types:
    name: Type check
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Check types
        run: yarn tsc
        working-directory: bundle

  release:
    name: Release
    needs: [build, test, lint, types]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Release
        run: yarn semantic-release
        working-directory: ./commercial/bundle
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          HUSKY: 0
